//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTranslated.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
                                                                                                                        
        /// <summary>
        ///   Looks up a localized string similar to Translation Mode.
        /// </summary>
        internal static string Translation_Mode {
            get {
                return ResourceManager.GetString("Translation Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Engine.
        /// </summary>
        internal static string TranslationEngine {
            get {
                return ResourceManager.GetString("TranslationEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use context.
        /// </summary>
        internal static string UseContext {
            get {
                return ResourceManager.GetString("UseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom prompt.
        /// </summary>
        internal static string UseCustomPrompt {
            get {
                return ResourceManager.GetString("UseCustomPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Custom Language.
        /// </summary>
        internal static string UseCustomTargetLanguage {
            get {
                return ResourceManager.GetString("UseCustomTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s do it!.
        /// </summary>
        internal static string WelcomeStr {
            get {
                return ResourceManager.GetString("WelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yell.
        /// </summary>
        internal static string Yell {
            get {
                return ResourceManager.GetString("Yell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
