//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTranslated.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatTranslated.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: API key will be stored as plain text in plugin configuration,
        ///any malware or third party plugins may have access to the key..
        /// </summary>
        internal static string APIKeyWarn {
            get {
                return ResourceManager.GetString("APIKeyWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Channels.
        /// </summary>
        internal static string ChatChannels {
            get {
                return ResourceManager.GetString("ChatChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include messages in current chat tab in LLM prompt..
        /// </summary>
        internal static string ChatContextExplanation {
            get {
                return ResourceManager.GetString("ChatContextExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Integration.
        /// </summary>
        internal static string ChatIntegration {
            get {
                return ResourceManager.GetString("ChatIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide original message when outputting translated message.
        /// </summary>
        internal static string ChatIntegration_HideOriginal {
            get {
                return ResourceManager.GetString("ChatIntegration_HideOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show colored text when outputting translated message.
        /// </summary>
        internal static string ChatIntegration_ShowColoredText {
            get {
                return ResourceManager.GetString("ChatIntegration_ShowColoredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output translated message to Echo channel.
        /// </summary>
        internal static string ChatIntegration_UseEchoChannel {
            get {
                return ResourceManager.GetString("ChatIntegration_UseEchoChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified).
        /// </summary>
        internal static string Chinese__Simplified_ {
            get {
                return ResourceManager.GetString("Chinese (Simplified)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Traditional).
        /// </summary>
        internal static string Chinese__Traditional_ {
            get {
                return ResourceManager.GetString("Chinese (Traditional)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell1.
        /// </summary>
        internal static string CrossLinkShell1 {
            get {
                return ResourceManager.GetString("CrossLinkShell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell2.
        /// </summary>
        internal static string CrossLinkShell2 {
            get {
                return ResourceManager.GetString("CrossLinkShell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell3.
        /// </summary>
        internal static string CrossLinkShell3 {
            get {
                return ResourceManager.GetString("CrossLinkShell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell4.
        /// </summary>
        internal static string CrossLinkShell4 {
            get {
                return ResourceManager.GetString("CrossLinkShell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell5.
        /// </summary>
        internal static string CrossLinkShell5 {
            get {
                return ResourceManager.GetString("CrossLinkShell5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell6.
        /// </summary>
        internal static string CrossLinkShell6 {
            get {
                return ResourceManager.GetString("CrossLinkShell6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell7.
        /// </summary>
        internal static string CrossLinkShell7 {
            get {
                return ResourceManager.GetString("CrossLinkShell7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossLinkShell8.
        /// </summary>
        internal static string CrossLinkShell8 {
            get {
                return ResourceManager.GetString("CrossLinkShell8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossParty.
        /// </summary>
        internal static string CrossParty {
            get {
                return ResourceManager.GetString("CrossParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Emote.
        /// </summary>
        internal static string CustomEmote {
            get {
                return ResourceManager.GetString("CustomEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the system prompt for translation.
        ///
        ///The text below shows the current prompt.
        ///Use {targetLanguage} as a placeholder for the target language.
        ///Context (if enabled) will be appended automatically.
        ///
        ///This prompt is shared between OpenAI and OpenAI-compatible APIs..
        /// </summary>
        internal static string CustomPromptTooltip {
            get {
                return ResourceManager.GetString("CustomPromptTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom system prompt.
        /// </summary>
        internal static string CustomSystemPrompt {
            get {
                return ResourceManager.GetString("CustomSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be forced to use Google translate if you use custom languages..
        /// </summary>
        internal static string CustomTargetLanguageExplanation {
            get {
                return ResourceManager.GetString("CustomTargetLanguageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom target language.
        /// </summary>
        internal static string CustomTargetLanguageHeader {
            get {
                return ResourceManager.GetString("CustomTargetLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepL API Key (Optional).
        /// </summary>
        internal static string DeepLAPIKey {
            get {
                return ResourceManager.GetString("DeepLAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepL will be used to translate chat messages. 
        ///Google and Bing translate will be used as backup.
        ///If DeepL API key is provided below, it will be used as backup instead..
        /// </summary>
        internal static string DeepLExplanation {
            get {
                return ResourceManager.GetString("DeepLExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s okay!.
        /// </summary>
        internal static string DomaStr {
            get {
                return ResourceManager.GetString("DomaStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable in duties.
        /// </summary>
        internal static string EnableInDuties {
            get {
                return ResourceManager.GetString("EnableInDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable plugin.
        /// </summary>
        internal static string EnablePlugin {
            get {
                return ResourceManager.GetString("EnablePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeCompany.
        /// </summary>
        internal static string FreeCompany {
            get {
                return ResourceManager.GetString("FreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        internal static string GenericChannels {
            get {
                return ResourceManager.GetString("GenericChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good game!.
        /// </summary>
        internal static string GGstr {
            get {
                return ResourceManager.GetString("GGstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        internal static string gp {
            get {
                return ResourceManager.GetString("gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: 
        ///DeepL have better accuracy in single-language translation. 
        ///LLM is better only if message is long or contain multiple languages..
        /// </summary>
        internal static string LLM_Explanation {
            get {
                return ResourceManager.GetString("LLM_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-hosted Gemini proxy.
        /// </summary>
        internal static string LLM_Proxy_Explanation {
            get {
                return ResourceManager.GetString("LLM_Proxy_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint URL.
        /// </summary>
        internal static string LLMApiEndpoint {
            get {
                return ResourceManager.GetString("LLMApiEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:
        ///https://api.openai.com/v1/chat/completions
        ///https://openrouter.ai/api/v1/chat/completions
        ///https://api.deepseek.com/chat/completions.
        /// </summary>
        internal static string LLMApiEndpointExample {
            get {
                return ResourceManager.GetString("LLMApiEndpointExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api key.
        /// </summary>
        internal static string LLMAPIKey {
            get {
                return ResourceManager.GetString("LLMAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string LLMModel {
            get {
                return ResourceManager.GetString("LLMModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLMProvider.
        /// </summary>
        internal static string LLMProvider {
            get {
                return ResourceManager.GetString("LLMProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls1.
        /// </summary>
        internal static string Ls1 {
            get {
                return ResourceManager.GetString("Ls1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls2.
        /// </summary>
        internal static string Ls2 {
            get {
                return ResourceManager.GetString("Ls2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls3.
        /// </summary>
        internal static string Ls3 {
            get {
                return ResourceManager.GetString("Ls3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls4.
        /// </summary>
        internal static string Ls4 {
            get {
                return ResourceManager.GetString("Ls4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls5.
        /// </summary>
        internal static string Ls5 {
            get {
                return ResourceManager.GetString("Ls5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls6.
        /// </summary>
        internal static string Ls6 {
            get {
                return ResourceManager.GetString("Ls6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls7.
        /// </summary>
        internal static string Ls7 {
            get {
                return ResourceManager.GetString("Ls7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ls8.
        /// </summary>
        internal static string Ls8 {
            get {
                return ResourceManager.GetString("Ls8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse translation.
        /// </summary>
        internal static string Main_Window_Reverse_translation {
            get {
                return ResourceManager.GetString("Main_Window_Reverse_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated text.
        /// </summary>
        internal static string Main_Window_Translated_text {
            get {
                return ResourceManager.GetString("Main_Window_Translated_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to translate..
        /// </summary>
        internal static string Main_Window_Translation_Failed {
            get {
                return ResourceManager.GetString("Main_Window_Translation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Languages.
        /// </summary>
        internal static string My_Languages {
            get {
                return ResourceManager.GetString("My_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages in these languages will not be translated..
        /// </summary>
        internal static string My_Languages_Explanation {
            get {
                return ResourceManager.GetString("My_Languages_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoviceNetwork.
        /// </summary>
        internal static string NoviceNetwork {
            get {
                return ResourceManager.GetString("NoviceNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May be restricted if you live in unsupported region..
        /// </summary>
        internal static string OpenAIAPIExplanation {
            get {
                return ResourceManager.GetString("OpenAIAPIExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI API Key.
        /// </summary>
        internal static string OpenAIAPIKey {
            get {
                return ResourceManager.GetString("OpenAIAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any custom providers with OpenAI-compatible API..
        /// </summary>
        internal static string OpenAICompatibleExplanation {
            get {
                return ResourceManager.GetString("OpenAICompatibleExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models without system role is not supported..
        /// </summary>
        internal static string OpenAICompatibleInfo {
            get {
                return ResourceManager.GetString("OpenAICompatibleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price estimation: $2.0 /month.
        /// </summary>
        internal static string OpenAIPriceEstimation {
            get {
                return ResourceManager.GetString("OpenAIPriceEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin UI Language.
        /// </summary>
        internal static string PluginUILanguage {
            get {
                return ResourceManager.GetString("PluginUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvPTeam.
        /// </summary>
        internal static string PvPTeam {
            get {
                return ResourceManager.GetString("PvPTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string Say {
            get {
                return ResourceManager.GetString("Say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See language list.
        /// </summary>
        internal static string SeeLanguageList {
            get {
                return ResourceManager.GetString("SeeLanguageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout.
        /// </summary>
        internal static string Shout {
            get {
                return ResourceManager.GetString("Shout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate to.
        /// </summary>
        internal static string TargetLang {
            get {
                return ResourceManager.GetString("TargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TellIncoming.
        /// </summary>
        internal static string TellIncoming {
            get {
                return ResourceManager.GetString("TellIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Mode.
        /// </summary>
        internal static string Translation_Mode {
            get {
                return ResourceManager.GetString("Translation Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Engine.
        /// </summary>
        internal static string TranslationEngine {
            get {
                return ResourceManager.GetString("TranslationEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use context.
        /// </summary>
        internal static string UseContext {
            get {
                return ResourceManager.GetString("UseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom prompt.
        /// </summary>
        internal static string UseCustomPrompt {
            get {
                return ResourceManager.GetString("UseCustomPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Custom Language.
        /// </summary>
        internal static string UseCustomTargetLanguage {
            get {
                return ResourceManager.GetString("UseCustomTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s do it!.
        /// </summary>
        internal static string WelcomeStr {
            get {
                return ResourceManager.GetString("WelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yell.
        /// </summary>
        internal static string Yell {
            get {
                return ResourceManager.GetString("Yell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
